import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
class Element{constructor(){this.hidden=false;this.disabled=false;this.textContent='';this.innerHTML='';this.style={};this.dataset={};this.value='';this.checked=false;this.classes=new Set();this.classList={add:(x)=>this.classes.add(x),remove:(x)=>this.classes.delete(x),contains:(x)=>this.classes.has(x),toggle:(x,on)=>{if(on??!this.classes.has(x))this.classes.add(x);else this.classes.delete(x);}};this.listeners={};}addEventListener(n,f){this.listeners[n]=f;}replaceChildren(){this.innerHTML='';}async decode(){}append(){}click(){} }
function setup(htmlPath,sourcePath,{saved,adminSession,fetcher}){
 const html=fs.readFileSync(new URL(htmlPath,import.meta.url),'utf8');const elements=new Map([...html.matchAll(/id="([^"]+)"/g)].map(m=>[m[1],new Element()]));if(elements.has('resultBox'))elements.get('resultBox').classList.add('hidden');
 const steps=Array.from({length:9},(_,i)=>{const e=new Element();e.dataset.step=String(i);return e;});
 const mem=new Map();if(saved)mem.set('dayi_checkout_v2',JSON.stringify(saved));if(adminSession)mem.set('dayi_admin_v2',JSON.stringify(adminSession));
 const storage={getItem:k=>mem.get(k)||null,setItem:(k,v)=>mem.set(k,v),removeItem:k=>mem.delete(k)};
 const context={crypto:globalThis.crypto,TextEncoder,Uint8Array,URL,URLSearchParams,AbortSignal,Request,Response,FormData,File,console,API_URL:'https://backend.test/api',PUBLIC_KEY:'public-test',SUPABASE_URL:'https://backend.test',document:{getElementById:id=>elements.get(id),querySelectorAll:s=>s==='.step'?steps:[],addEventListener(){},hidden:false,createElement:()=>new Element()},window:{scrollTo(){}},matchMedia:()=>({matches:true}),localStorage:storage,sessionStorage:storage,location:{href:'https://dayi.example/',hash:'',search:'',pathname:'/'},indexedDB:{open(){const r={};queueMicrotask(()=>r.onerror());return r;}},fetch:fetcher,setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,navigator:{}};
 let src=fs.readFileSync(new URL(sourcePath,import.meta.url),'utf8').replace(/^import .*;\n/,'').replaceAll('export async function','async function');
 if(saved)src=src.replace(/init\(\);\s*$/, 'globalThis.ready=init();globalThis.testAPI={poll,getState:()=>state};');else src=src.replace('if(session)load().catch', 'if(session)globalThis.ready=load().catch');
 vm.createContext(context);vm.runInContext(src,context);return {context,e:elements,steps,ready:()=>context.ready};
}
const state={step:8,needs:['休闲喝茶'],style:'东方自然',yardSize:'不确定',order_code:'DAYI-260919-1234567890',access_token:'a'.repeat(64),request_id:'123e4567-e89b-42d3-a456-426614174000',has_photo:true,submitted:true};
function customer(saved,data){return setup('../direction-feedback/index.html','../direction-feedback/app.mjs',{saved,fetcher:async(url,opts)=>Response.json(url.endsWith('/analytics_events')?{}:data)});}
test('reload returns directly to the saved submitted order',async()=>{const h=customer(state,{checkout_stage:'submitted',process_status:'waiting_payment_verification',has_photo:true});await h.ready();await new Promise(setImmediate);assert.equal(h.steps[8].classList.contains('active'),true);assert.equal(h.e.get('statusTitle').textContent,'等待付款确认');});
test('a returned image without three advice entries never displays completed',async()=>{const h=customer(state,{checkout_stage:'submitted',process_status:'completed',has_photo:true,image_url:'https://image.test/r.jpg',advice:[]});await h.ready();await new Promise(setImmediate);assert.equal(h.e.get('resultBox').classList.contains('hidden'),true);assert.notEqual(h.e.get('statusTitle').textContent,'你的方向反馈已完成');});
test('a fully loaded image and three advice entries unlock delivery',async()=>{const h=customer(state,{checkout_stage:'submitted',process_status:'completed',has_photo:true,image_url:'https://image.test/r.jpg',advice:['建议一','建议二','建议三']});await h.ready();await new Promise(setImmediate);assert.equal(h.e.get('resultBox').classList.contains('hidden'),false);assert.equal(h.e.get('statusTitle').textContent,'你的方向反馈已完成');});
test('a failed original upload cannot reveal payment on reload',async()=>{const h=customer({...state,submitted:false,has_photo:false},{checkout_stage:'draft',has_photo:false,has_proof:false});await h.ready();await new Promise(setImmediate);assert.equal(h.steps[1].classList.contains('active'),true);assert.equal(h.steps[7].classList.contains('active'),false);});
test('a locally replaced original is not mistaken for the previous server upload',async()=>{const h=customer({...state,submitted:false,photo_dirty:true},{checkout_stage:'draft',has_photo:true,has_proof:false});await h.ready();await new Promise(setImmediate);assert.equal(h.steps[1].classList.contains('active'),true);assert.equal(h.context.testAPI.getState().has_photo,false);});
test('the admin retry uses the refreshed bearer token',async()=>{const auth=[];const h=setup('../direction-feedback/dashboard/index.html','../direction-feedback/dashboard/admin.mjs',{adminSession:{access_token:'old',refresh_token:'refresh',expires_at:9999999999},fetcher:async(url,opts)=>{if(url.includes('grant_type=refresh_token'))return Response.json({access_token:'new',refresh_token:'refresh2',expires_at:9999999999});auth.push(opts.headers.Authorization);if(opts.headers.Authorization==='Bearer old')return Response.json({message:'expired'},{status:401});const b=JSON.parse(opts.body);if(b.action==='admin_business_status')return Response.json({config:{enabled:false},calibration:{required_types:[],approved_types:[]},image_key_configured:false});if(b.action==='admin_business_orders')return Response.json({orders:[]});return Response.json({});}});await h.ready();assert.equal(auth.filter(x=>x==='Bearer old').length,1);assert.equal(auth.filter(x=>x==='Bearer new').length,3);});
function paymentHarness(fetcher){return setup('../direction-feedback/index.html','../direction-feedback/app.mjs',{saved:{...state,step:6,order_code:null,submitted:false},fetcher:async(url,opts)=>url.endsWith('/analytics_events')?Response.json({}):fetcher(JSON.parse(opts.body))});}
test('payment click immediately preserves the actual QR and contact fields while saving',async()=>{let resolveCreate;const h=paymentHarness(()=>new Promise(r=>{resolveCreate=r;}));await h.ready();const pending=h.e.get('toPay').listeners.click();assert.equal(h.steps[7].classList.contains('active'),true);assert.match(h.e.get('paymentStatus').textContent,/正在保存/);assert.equal(h.e.get('paymentControls').hidden,false);assert.equal(h.e.get('paymentQr').hidden,false);assert.equal(h.e.get('saveQr').disabled,false);resolveCreate(Response.json({order_code:state.order_code,has_photo:true}));await pending;});
test('checkout saves intake without consulting model readiness',async()=>{const calls=[];const h=paymentHarness(b=>{calls.push(b.action);return Response.json({order_code:state.order_code,has_photo:true});});await h.ready();await h.e.get('toPay').listeners.click();assert.deepEqual(calls,['create']);assert.equal(h.e.get('submitOrder').disabled,false);assert.equal(h.e.get('paymentQr').hidden,false);});
test('a saved photo enables order submission',async()=>{const h=paymentHarness(()=>Response.json({order_code:state.order_code,has_photo:true}));await h.ready();await h.e.get('toPay').listeners.click();assert.equal(h.e.get('submitOrder').disabled,false);assert.match(h.e.get('paymentStatus').textContent,/可以扫码付款/);});
test('a save failure retains QR and contact but prevents an unsaved submission',async()=>{const h=paymentHarness(()=>{throw Error('offline');});await h.ready();await h.e.get('toPay').listeners.click();assert.match(h.e.get('paymentStatus').textContent,/连接暂时中断/);assert.equal(h.e.get('retryPayment').disabled,false);assert.equal(h.e.get('paymentControls').hidden,false);assert.equal(h.e.get('paymentQr').hidden,false);assert.equal(h.e.get('submitOrder').disabled,true);assert.equal(h.e.get('toPay').disabled,false);});
